config/routes.rb
Rails.application.routes.draw do

  
  resources :carts, except:[:index, :new, :edit]
  resources :cart_items, only:[:create, :update, :destroy]

  devise_for :users do
    resources :orders, only: [:new, :create]
  end
  
  resources :users, only:[:show]
  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  root "items#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :nullify, dependent: :destroy
  has_many :items, through: :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartsHelper
  before_action :require_login
  before_action :only_current_cart

  def show
    @items_in_cart = CartItem.where(cart_id:current_user.cart)
  end

  def create

  end

  def update

  end

  def destroy

  end
  
end

app/helpers/carts_helper.rb
module CartsHelper

  private

  def require_login
    unless current_user != nil
        redirect_to new_user_session_path
    end
  end

  def only_current_cart
    if current_user != nil && current_user.cart.id != params[:id].to_i
        return redirect_to cart_path(current_user.cart.id)
    end
  end

end

app/views/carts/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Carts#create</h1>
  <p>Find me in app/views/carts/create.html.erb</p>
</div>

app/views/carts/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Carts#destroy</h1>
  <p>Find me in app/views/carts/destroy.html.erb</p>
</div>

app/views/carts/show.html.erb
<div class="relative overflow-x-auto shadow-md sm:rounded-lg">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400 nav-color powder">
      <tr>
        <th scope="col" class="px-6 py-3 text-center">
          <span class="sr-only">Image</span>
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Produit
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Quantité
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Prix unitaire
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Action
        </th>
      </tr>
    </thead>
    <tbody>
    
      <% total_price = [] %>
      <% @orders = [] %>
      <% @items_in_cart.each do |item| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 powder">
          <td class="w-32 p-4">
            <%= image_tag rails_blob_path(item.item.image), class:"pic-item" if item.item.image.attached? %>

          </td>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white text-center">
            <%= item.item.title %>
          </td>
          <td class="px-6 py-4 text-center">
            <div class="flex items-center space-x-3">
              <div>
                <input type="number" id="first_product" class="bg-gray-50 w-14 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block px-2.5 py-1 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="1" required>
              </div>
            </div>
          </td>
          <td class="px-6 py-4 font-semibold text-gray-900 dark:text-white text-center">
            <%= total_item = add_zero(item.item.price) %> €
          </td>
          <td class="px-6 py-4 text-center">
            <%= button_to "Retirer", cart_item_path(item.item_id, from_cart: true), class:"font-medium text-red-600 dark:text-red-500 hover:underline", method: :delete %>
          </td>
        </tr>
        <% total_item = item.item.price %>
        <% total_price << total_item %>
        <% @orders << item.item %>
      <% end %>
    </tbody>
  </table>

  <div class="nav-item-color powder">
    <%if @items_in_cart.length>0%>
    <div class="total">

    <%total_amount = total_price.inject(0){|sum,x| sum + x }%>
        <p class = "m-2">Prix total: <%= add_zero(total_amount) %> € &nbsp</p>

        <%= button_to "Confirmer la commande", checkout_create_path(total_amount: total_amount, orders: @orders), class: "m-2 bg-amber-500 hover:bg-amber-600 text-white font-bold py-1 px-8 border-b-4 border-amber-600 hover:border-amber-700 rounded", data: {turbo: false} %>

    </div>
      <%else%>
      <div class = "text-center py-2">
        <p>Panier vide. &nbsp</p>
      </div>
    <%end%>
    
  </div>

</div>

app/views/carts/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Carts#update</h1>
  <p>Find me in app/views/carts/update.html.erb</p>
</div>