config/routes.rb
Rails.application.routes.draw do

  
  resources :carts, except:[:index, :new, :edit]
  resources :cart_items, only:[:create, :update, :destroy]

  devise_for :users do
    resources :orders, only: [:new, :create]
  end
  
  resources :users, only:[:show]
  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  root "items#index"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :nullify, dependent: :destroy
  has_many :carts, through: :cart_items
  has_many :order_items
  has_many :orders, through: :order_items
  has_one_attached :image
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]

  # GET /items or /items.json
  def index
    @items = Item.all
    @cart_item = CartItem.new
    @in_cart_items = CartItem.all;
  end

  # GET /items/1 or /items/1.json
  def show
    @items = Item.all
    @cart_item = CartItem.new
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, html: { class: "space-y-4 md:space-y-6" }) do |form| %>
  <% if item.errors.any? %>
    <div class="text-red-500">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :title, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div>
    <%= form.label :description, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_area :description, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div>
    <%= form.label :price, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :price, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div>
    <%= form.label :image_url, class: "block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
    <%= form.text_field :image_url, class: "bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "w-full text-white bg-blue-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow back-total relative">

  <div class="ind-pic">
    <% if item.image.attached? %>
      <%= link_to item do %>
        <%= image_tag item.image, class: "w-150 h-150 p-8 ind-item", alt: "product image" %>
      <% end %>
    <% end %>
  </div>

  <div class="px-5 pb-5">
    <div id="texts" class="text-center">
      <a href="#">
        <h5 class="text-xl font-semibold tracking-tight text-gray-900 dark:text-white"><%= link_to item.title, item %></h5>
      </a>
      <p class="text-sm text-slate-700">
        <%= link_to item do %>
          <%= item.description %>
        <% end %>
      </p>
    </div>
    <br><br><br>
    <div id="bottom" class="flex items-center justify-between absolute bottom-0 left-0 right-0">
      <span class="text-3xl font-bold text-gray-900 dark:text-white mrg-price-cart">
        <%=add_zero(item.price)%> €
      </span>

      <%= button_to "", ""%>
      <% if user_signed_in? %>
        <% ordered = current_user.ordered_item?(item) %>
        <%= form_for @cart_item, url: ordered ? cart_item_path(id: item.id, from: "product") : cart_items_path, :method => ordered ? :delete : :post do |f| %>
          <%= f.hidden_field :item_id, value: item.id %>
          <%= f.hidden_field :cart_id, value: current_user.cart.id %>
          <button class="h-10 px-6 font-semibold rounded-md bard-btn mrg-btn-cart <%= 'grey-button h-10 px-6 font-semibold rounded-md mrg-btn-cart' if ordered %> " type="submit">
            <%= ordered ? "Retirer du panier" : "Ajouter au panier" %>
          </button>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/items/_product.html.erb
<!-- This is an example component -->
<div>
	
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/tailwindcss@2.0.1/dist/tailwind.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,400;0,600;0,700;1,400&amp;display=swap'>

</head>
<body class="antialiased">
  
  <!-- ./ Breadcrumbs -->

  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6">
    <div class="flex flex-col md:flex-row -mx-4">
      <div class="md:flex-1 px-4">
        <div x-data="{ image: 1 }" x-cloak>
          <div class="flex items-center justify-center">
             <%= image_tag @item.image, class: "rounded-full", alt: "Item Image" %>
          </div>

          <p class = "text-center pt-6 text-slate-950">Contenu similaire</p><br>

          <div class="flex -mx-2 mb-4">
            <% used_items = [@item] %>
            <% for i in 0..3 %>
            <% item = @items.sample(1).first %>
              <% while used_items.include?(item) %>
                <% item = @items.sample(1).first %>
              <% end %>
              <% used_items << item %>
              <div class="flex-1 px-2">
                <%= link_to item_path(item) do %>
                  <% if item.image.attached? %>
                    <%= image_tag item.image, class: "rounded", alt: "Item Image" %>
                  <% end %>
                <% end %>

              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="md:flex-1 px-4">
        <h2 class="mb-2 leading-tight tracking-tight font-bold text-gray-800 text-2xl md:text-3xl"><%= @item.title %></h2>

        <div class="flex items-center space-x-4 my-4">
          <div>
            <div class="rounded-lg bg-gray-100 flex py-2 px-3">
              <span class="font-bold text-indigo-600 text-3xl"> <%=add_zero(@item.price)%> €</span>
            </div>
          </div>
        </div>

        <p class="text-gray-500"><%= @item.description %></p>

        <div class="flex py-4 space-x-4">
          <div class="relative">
            <div class="text-center left-0 pt-2 right-0 absolute text-xs uppercase text-gray-400 font-semibold">Quantité</div>
            
            
            <select class="cursor-pointer appearance-none rounded-xl border border-gray-200 pl-4 pr-8 h-14 flex items-end pb-1">
              <option>1</option>
              <option>2</option>
              <option>3</option>
              <option>4</option>
              <option>5</option>
            </select>

            

            <svg class="w-5 h-5 text-gray-400 absolute right-0 bottom-0 mb-2 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
            </svg>
          </div>

        <% if user_signed_in? %>
          <% ordered = current_user.ordered_item?(@item) %>
          <%= form_for @cart_item, url: ordered ? cart_item_path(id: @item.id) : cart_items_path, :method => ordered ? :delete : :post do |f| %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :cart_id, value: current_user.cart.id %>
            <button class="h-10 px-6 font-semibold rounded-md bard-btn mrg-btn-cart <%= 'grey-button h-10 px-6 font-semibold rounded-md mrg-btn-cart' if ordered %> " type="submit">
              <%= ordered ? "Retirer du panier" : "Ajouter au panier" %>
            </button>
          <% end %>
        <% else %>
        <% end %>

        </div>

      </div>
    </div>
  </div>
</div>
  </body>
<!-- partial -->
  <script src='https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.7.3/dist/alpine.min.js'></script>
</html>

</div>

app/views/items/edit.html.erb
<section class= "bg-gray-50 dark:bg-gray-900">
  <div class="flex flex-col items-center justify-center px-6 py-6 ">
    <%= link_to root_path, class: "flex items-center mb-6 text-2xl font-semibold text-gray-900 dark:text-white" do %>
      <%= image_tag "http://lofrev.net/wp-content/photos/2014/09/Cat-logo.gif", alt: "logo", class: "w-8 h-8 mr-2" %>
      Projet Chatons     
    <% end %>
    <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
      <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
        <h1 class="text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
          Mettre à jour l'item
        </h1>
        <%= render "form", item: @item, html: { class: "space-y-4 md:space-y-6" } %>
        <div class="flex justify-between">
          <%= link_to "Montrer l'item", @item, class: "text-blue-600 hover:underline" %> 
          <%= link_to "Retour à la liste", items_path, class: "text-blue-600 hover:underline" %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/items/index.html.erb
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
  <% @items.each do |item| %>
    <%= render item %>
  <% end %>
</div>

app/views/items/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New item</h1>

  <%= render "form", item: @item %>

  <%= link_to 'Back to items', items_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/items/show.html.erb
<%= render 'product' %>