config/routes.rb
Rails.application.routes.draw do

  
  resources :carts, except:[:index, :new, :edit]
  resources :cart_items, only:[:create, :update, :destroy]

  devise_for :users do
    resources :orders, only: [:new, :create]
  end
  
  resources :users, only:[:show]
  resources :items

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  root "items#index"
end

app/views/layouts/_footer.html.erb
<footer class="relative bg-blueGray pt-2.5">
  <div class="container mx-auto px-4">
    <div class="flex flex-wrap text-left lg:text-left items-center justify-between">
      <div class="w-full lg:w-6/12 px-4">
        <h4 class="text-3xl font-semibold text-blueGray-700">Le Projet des Chatons pour THP</h4>
      </div>
      <div class="w-full lg:w-6/12 px-4 flex justify-end">
        <button class="bg-white text-lightBlue-400 shadow-lg font-normal h-10 w-10 items-center justify-center align-center rounded-full outline-none focus:outline-none mr-2" type="button">
          <a href="https://github.com/TeamKiTu/Projet-chatons" target="_blank"><i class="fab fa-github"></i></a>
        </button>
      </div>
    </div>

    <hr class="my-2.5 border-blueGray-300">

    <section class="page-section" id="team">
      <div class="container">
        <div class="grid grid-cols-5 gap-4">
          <div>
            <div class="team-member text-center">
              <img src="<%= asset_path('1.jpg') %>" class="h-16 w-16 rounded-full justify-items-center mx-auto cursor-pointer" alt="..." onclick="openModal('<%= asset_path('1.jpg') %>', 'Specialiste des chatons aquatiques')">
              <h4>Nicolas Vadelorge</h4>
                          <p class="text-muted text-center">Founder</p>
                          <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                          <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                          <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                      </div>
                        <div class="auto-cols-auto">
                            <div class="team-member text-center">
              <img src="<%= asset_path('2.jpg') %>" class="h-16 w-16 rounded-full justify-items-center mx-auto cursor-pointer" alt="..." onclick="openModal('<%= asset_path('2.jpg') %>', 'Specialiste des chatons voyageurs')">
                    <h4 class="text-center">Emmanuel Beaugendre</h4>
                    <p class="text-muted text-center">Founder</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Diana Petersen LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="auto-cols-auto">
                <div class="team-member text-center">
              <img src="<%= asset_path('3.jpg') %>" class="h-16 w-16 rounded-full justify-items-center mx-auto cursor-pointer" alt="..." onclick="openModal('<%= asset_path('3.jpg') %>', 'Specialiste des chatons philosophes')">
                    <h4 class="text-center">Nicolas Chiron</h4>
                    <p class="text-muted text-center">Founder</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Larry Parker LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="auto-cols-auto">
                <div class="team-member text-center">
              <img src="<%= asset_path('4.jpg') %>" class="h-16 w-16 rounded-full justify-items-center mx-auto cursor-pointer" alt="..." onclick="openModal('<%= asset_path('4.jpg') %>', 'Specialiste des chatons gamers')">
                    <h4 class="text-center">Vincent Deloffre</h4>
                    <p class="text-muted text-center">Founder</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="auto-cols-auto">
                <div class="team-member text-center">
              <img src="<%= asset_path('5.jpg') %>" class="h-16 w-16 rounded-full justify-items-center mx-auto cursor-pointer" alt="..." onclick="openModal('<%= asset_path('5.jpg') %>', 'Specialiste des chatons randonneurs')">
                    <h4 class="text-center">Guillaume Regimbeau</h4>
                    <p class="text-muted text-center">Founder</p>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Twitter Profile"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand Facebook Profile"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!" aria-label="Parveen Anand LinkedIn Profile"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>

    <hr class="my-4 border-blueGray-300">

    <div class="flex flex-wrap items-center md:justify-between justify-center">
      <div class="w-full md:w-4/12 px-4 mx-auto text-center">
        <div class="text-sm text-blueGray-500 font-semibold py-1">
          Copyright © <span id="get-current-year">2023</span>
          <a href="https://www.thehackingproject.org/" class="text-blueGray-500 hover:text-blueGray-800">| Le Projet des Chatons pour THP |</a>
        </div>
      </div>
    </div>
  </div>

<div id="modal" class="fixed z-10 inset-0 overflow-y-auto hidden" aria-labelledby="modal-title" role="dialog" aria-modal="true">
  <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

    <!-- Contenu de la modal -->
    <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
      <img id="modalImage" class="w-full" src="" alt="Modal Image">
      <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
        <button id="closeModal" type="button" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none sm:ml-3 sm:w-auto sm:text-sm">
          Fermer
        </button>
      </div>
      <p id="modalCaption"></p> <!-- Ajout de l'élément pour afficher la légende -->
    </div>
  </div>
</div>

<script>
  function openModal(imageUrl, caption) {
    var modal = document.getElementById("modal");
    var modalImage = document.getElementById("modalImage");
    var modalCaption = document.getElementById("modalCaption");

    modalImage.src = imageUrl;
    modalCaption.textContent = caption;
    modal.classList.remove("hidden");
  }

  function closeModal() {
    var modal = document.getElementById("modal");
    modal.classList.add("hidden");
  }

  document.getElementById("closeModal").addEventListener("click", closeModal);
</script>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="bg-white border-gray-200 dark:bg-gray-900 dark:border-gray-700 nav-color fixed top-0 left-0 w-full bg-white shadow-lg z-50">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="<%= root_path %>" class="flex items-center">
      <%= image_tag("paw.png", class: "h-10 w-10 mr-3", alt: "Flowbite Logo") %>
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white powder"><span class="primary">P</span>rojet <span class="primary">C</span>haton</span>
    </a>
    <button data-collapse-toggle="navbar-dropdown" id ="navbar" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-dropdown" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-dropdown">
      <ul class="nav-item-color flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavbar" class="flex flex-col items-center justify-between w-full py-2 pl-3 pr-4 text-gray-900 bg-transparent">
            <div class="w-10 h-10 rounded-full overflow-hidden bg-orange-400 flex items-center justify-center">
              <%= image_tag("cart.png", class: "w-7 h-7 object-cover rounded-full") %>
            </div>
            <% if current_user %>
              <% if current_user.cart.cart_items.count == 1 %>
                <div class="text-white block px-4 py-2"><%= current_user.cart.cart_items.count %> article</strong>
              <% elsif current_user.cart.cart_items.count > 1 %>
                <div class="text-white block px-4 py-2"><%= current_user.cart.cart_items.count %> articles</strong>
              <% else %>
                <div class="text-white block px-4 py-2">Votre panier est vide</strong>
              <% end %>
            <% else %>
              <div class="text-white block px-4 py-2">Votre panier est vide</strong>
            <% end %>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownNavbar" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <% if current_user %>
            <div class="py-1">
              <%= link_to "Afficher le panier", cart_path(current_user.id), class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white" %>
            </div>
            <% if current_user&.orders.count > 0 %>
              <%= link_to "Historique d'achat", user_path(current_user.id), class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-400 dark:hover:text-white" %>
            <% end %>
            <% else %>
              <p class="text-center">Votre panier est vide. <%= link_to "Connectez-vous pour commencer a le remplir.", new_user_session_path, class:"block px-4 py-2 hover:bg-gray-100 primary" %></p>
            <% end %>
          </div>
        </li>
        <li>
          <button id="dropdownNavbarLink" data-dropdown-toggle="dropdownNavUser" class="flex flex-col items-center justify-center w-full py-2 pl-3 pr-4 text-gray-900 bg-transparent">
            <div class="w-10 h-10 rounded-full overflow-hidden bg-orange-400 flex items-center justify-center">
              <%= image_tag("user.png", class: "w-7 h-7 object-cover rounded-full") %>
            </div>
            <% if current_user %>
              <div class="text-white block px-4 py-2"><%= current_user.email %></div>
            <% end %>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdownNavUser" class="z-10 hidden font-normal bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-400" aria-labelledby="dropdownLargeButton">
              <% if current_user %>
              <li>
                <%= link_to "Editer son profil", edit_user_registration_path(current_user), class:"block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
              </li>
              <li>
                <%= link_to "Se déconnecter", destroy_user_session_path, class:"block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white",form: { data: { turbo_confirm: "Veux-tu te déconnecter ?" } }, method: :delete %>
              </li>
              <% else %>
              <li>
                <%= link_to "Se connecter", new_user_session_path, class:"block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
              </li>
              <li>
                <%= link_to "Créer un compte", new_user_registration_path, class:"block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
              </li>
              <% end %>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class ="container mx-auto py-20"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projet Chatons</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yatra+One&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous"/>

    <script src="https://cdn.tailwindcss.com"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main class="container mx-auto mt-8 px-1 pb-10 flex justify-center items-center">
      <%= yield %>
    </main>
    <br><%= render 'layouts/footer'%>

      <script src="https://unpkg.com/flowbite@1.5.1/dist/flowbite.js"></script>
  </body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>
</html>